title: Fullstack development techniques
author: pgatic
email: pgatic@hotmail.com
description: github pages introduction and exploring

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  pgatic # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
